guild_a:
  # current guild
  name: Monolith
  current_havoc: 7920
  tokens_remaining: 20
  # opposing guild
  max_stronghold_hp: 800
  max_defense_tower_hp: 450
  max_satellite_hp: 200
  fortresses:
    - stronghold: {hp: 0}
      defense_towers: [{hp: 30}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 80}, {hp: 80}, {hp: 0}, {hp: 0}, {hp: 0}]

    - stronghold: {hp: 500}
      defense_towers: [{hp: 0}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 80}, {hp: 0}, {hp: 0}]

    - stronghold: {hp: 500}
      defense_towers: [{hp: 0}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 80}, {hp: 80}]

guild_b:
  # current guild
  name: Not Monolith
  current_havoc: 6810
  tokens_remaining: 42
  # opposing guild
  max_stronghold_hp: 920
  max_defense_tower_hp: 540
  max_satellite_hp: 200
  fortresses:
    - stronghold: {hp: 0}
      defense_towers: [{hp: 0}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}]

    - stronghold: {hp: 320}
      defense_towers: [{hp: 0}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 140}]

    - stronghold: {hp: 740}
      defense_towers: [{hp: 180}, {hp: 0}]
      satellites: [{hp: 200}, {hp: 200}, {hp: 200}, {hp: 200}, {hp: 80}, {hp: 80}]
